---
platform: linux

inputs:
- name: pipeline-resources
- name: stembuild

params:
  vcenter_host: ((vcenter-host))
  vcenter_username: ((vcenter-username))
  vcenter_password: ((vcenter-password))
  vcenter_datacenter: ((vcenter-datacenter))
  vcenter_ca_certs: ((vcenter-ca-certs))

  vm_folder: ((vm-folder))
  
  vmware_tools_status: ((vmware-tools-status))
  timeout: ((timeout))

outputs:
- name: stemcell
  
run:
  path: pipeline-resources/tasks/package.sh
