---
platform: linux

inputs:
- name: pipeline-resources

params:
  vcenter_host: ((vcenter-host))
  vcenter_username: ((vcenter-username))
  vcenter_password: ((vcenter-password))
  vcenter_datacenter: ((vcenter-datacenter))
  vcenter_ca_certs: ((vcenter-ca-certs))

  base_vm_name: ((base-vm-name))
  vm_folder: ((vm-folder))
  admin_password: ((admin-password))

  vmware_tools_status: ((vmware-tools-status))
  timeout: ((timeout))
  
run:
  path: pipeline-resources/tasks/update-base.sh
